### ISSUE TITLE
 My DSA Syllabus Tracker

### ISSUE THREAD

**Issue by om15-EC** [om15-EC/DSA-Bootcamp-Java#1]
- [x] Introduction to Java
    - [x]  Introduction 
    - [x] How it works 
    - [x] Setup Installation 
    - [x] Input and output in java
    - [x] Conditional & loops in java
        - [x] If else 
        - [x] loops
        - [x] switch statement
- [ ] Data types
- [ ] Coding best practices
- [ ] Functions
    - [ ]  Introduction 
    - [ ] Scoping in Java
    - [ ] Shaowing
    - [ ] Overloading
- [ ] Arrays
    - [ ] Introduction
    - [ ] Memory Management
    - [ ] Input and output 
    - [ ] ArrayList introduction
    - [ ] Sorting
        - [ ] Linear search
        - [ ] Binary Search
        - [ ] Modified Binary search
        - [ ] 11th Binary search on 2D array
- [ ] Strings
